### ISSUE TITLE
Except_files seems to delete all files 

### ISSUE THREAD

**Issue by davidrustingha** [chomupashchuk/delete-file-home-assistant#8]
I have an automation set up to delete all motion detection files older than seven days, except the base_image I use. But even though setting the exception it still deleted all files.

```
    - service: delete.files_in_folder
      data:
        folder: /config/www/doods
        time: 604800
        except_files:
          - 'doods_baseimage.jpg'
```
